baseurl = "https://srefrance.org/"
languageCode = "en-us"
title = "SRE France"
theme = "beautifulhugo"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
enableRobotsTXT = true

pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[Params]
  homeTitle = "SRE France"
  organizationName = "SRE France"
  organizationLogo = "img/logo.png"
  organizationAddress = "FR"
  foundingDate = "2022"
  nonprofitStatus = "Nonprofit501c3"
  socialProfiles = ["https://piaille.fr/@srefrance", "https://bsky.app/profile/srefrance.bsky.social", "https://github.com/sre-france/", "https://www.meetup.com/Site-Reliability-Engineering-France/"]
  knowsAbout = ["Site Reliability Engineering", "DevOps", "Cloud Infrastructure", "Open Source"]
  subtitle = "Site Reliability Engineers in France"
  mainSections = ["post","posts"]
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = false
  delayDisqus = true
  showRelatedPosts = true
  hideAuthor = true
  since = 2022

[[Params.bigimg]]
  src = "img/bigimg-01.webp"
  desc = ""
  position = "center top"
[[Params.bigimg]]
  src = "img/bigimg-02.webp"
  desc = ""
  position = "center top"
[[Params.bigimg]]
  src = "img/bigimg-03.webp"
  desc = ""
  position = "center top"

[Params.author]
  name = "SRE France Association"
  github = "sre-france"
  telegram = "+lH1dMlrK0q5hNTk8"
  youtube = "@srefrance"
  twitter = "SREFrance"
  bluesky = "srefrance.bsky.social"
  mastodon = "piaille.fr/@srefrance"
  email = "srefranceasso@gmail.com"

[[menu.main]]
    name = "Meetups"
    url = "tags/meetup/"
    weight = 1

[[menu.main]]
    name = "Summer Camp"
    url = "tags/summercamp/"
    weight = 2

[[menu.main]]
    name = "Github"
    url = "https://github.com/sre-france/"
    weight = 3

[[menu.main]]
    name = "Job Board"
    url = "page/job-board/"
    weight = 4

[[menu.main]]
    name = "Contact"
    url = "page/contact/"
    weight = 5

[[menu.main]]
    name = "Donations"
    url = "https://www.helloasso.com/associations/sre-france/formulaires/1"
    weight = 6

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 7
